/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication17;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tahsin Mubarak
 */
public class ATTNDENCE_GIVE extends javax.swing.JFrame {
String primary_key;
    /**
     * Creates new form ATTNDENCE_GIVE
     */
    public ATTNDENCE_GIVE() {
        initComponents();
        //EDIT_COMBO_BOX();
        //refresh();
    }
    
    public String datesetter(String fate){
    String yyyy="";
   String mm="";
   String dd="";
   String mmm="";
   for(int i=0;i<4;i++){
   yyyy+=fate.charAt(i);
   }
  System.out.println(yyyy);
     for(int i=5;i<7;i++){
   mm+=fate.charAt(i);
   }
   System.out.println(mm);
     for(int i=8;i<10;i++){
   dd+=fate.charAt(i);
   }
     System.out.println(dd);
   if(Integer.parseInt(mm)==1){
   mmm="Jan";
   }
   if(Integer.parseInt(mm)==2){
   mmm="Feb";
   }
   if(Integer.parseInt(mm)==3){
   mmm="Mar";
   }
   if(Integer.parseInt(mm)==4){
   mmm="Apr";
   }
   if(Integer.parseInt(mm)==5){
   mmm="May";
   }
   if(Integer.parseInt(mm)==6){
   mmm="Jun";
   }
   if(Integer.parseInt(mm)==7){
   mmm="Jul";
   }
   if(Integer.parseInt(mm)==8){
   mmm="Aug";
   }
   if(Integer.parseInt(mm)==9){
   mmm="Sep";
   }
   if(Integer.parseInt(mm)==10){
   mmm="Oct";
   }
   if(Integer.parseInt(mm)==11){
   mmm="Nov";
   }
   if(Integer.parseInt(mm)==10){
   mmm="Dec";
   }
   System.out.println(mmm);
   String date=dd+"-"+mmm+"-"+yyyy;
   System.out.println(date);
   return date;
    }
    
    public void primay_key(String p){
    primary_key=p;
     EDIT_COMBO_BOX();
     refresh();
    }
    
    public static Connection ConnerDB() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Student", "1234");
            return con;
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
        
    }
    
    void EDIT_COMBO_BOX(){
     Connection conn=ConnerDB();
     try{
     Statement st=conn.createStatement();
         ResultSet rs=st.executeQuery("SELECT UNIQUE CLASS_DATE FROM TAKES,ATTEND,CLASS WHERE T_CLASS_NO=C_CLASS_NO AND C_CLASS_NO=CLASS_NO AND T_FACULTY_ID="+primary_key);
         while(rs.next()){
         jComboBox2.addItem(rs.getDate(1).toString());
         } 
         
         rs.close();
     }catch(Exception e){
     e.printStackTrace();
     }
          try{
     Statement st=conn.createStatement();
         ResultSet rs=st.executeQuery("SELECT UNIQUE CLASS_TIME FROM TAKES,ATTEND,CLASS WHERE T_CLASS_NO=C_CLASS_NO AND C_CLASS_NO=CLASS_NO AND T_FACULTY_ID="+primary_key);
         while(rs.next()){
         jComboBox1.addItem(rs.getString(1).toString());
         } 
         
         rs.close();
     }catch(Exception e){
     e.printStackTrace();
     }
    }
    void refresh(){
            Connection conn=ConnerDB();
        DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
        RecordTable.setRowCount(0);
        try{
     Statement st=conn.createStatement();
     String date=datesetter(jComboBox2.getSelectedItem().toString());
     System.out.println(date);
     String sql="SELECT * FROM TAKES,ATTEND,CLASS WHERE T_CLASS_NO=C_CLASS_NO AND C_CLASS_NO=CLASS_NO AND T_FACULTY_ID="+primary_key+" and class_date='"+date+"' AND CLASS_TIME='"+jComboBox1.getSelectedItem()+"'";     //'10:00-11:00'";
         ResultSet rs=st.executeQuery(sql);
         while(rs.next()){
         Vector columnData=new Vector();
         columnData.add(rs.getInt(1));
         columnData.add(rs.getString(7));
         columnData.add(rs.getString(4));
         columnData.add(rs.getString(5));
         RecordTable.addRow(columnData);
         } 
         
         rs.close();
     }catch(Exception e){
     e.printStackTrace();
     }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 240, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CLASS_NO", "COURSE_CODE", "STUDENT_ID", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 1280, 350));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 290, -1));

        jButton1.setText("ABSENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 170, -1));

        jButton2.setText("PRESENT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 170, -1));

        jButton3.setText("refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    refresh();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
       int selectedRow=jTable1.getSelectedRow();
        Connection conn=ConnerDB();
        try{
        String sql = "update attend set C_ATTEND=? WHERE C_CLASS_NO=? AND C_STUDENT_ID=?";
            PreparedStatement pst = null;
            pst = conn.prepareStatement(sql);
            pst.setString(1,  "PRESENT");
            pst.setString(2, jTable1.getValueAt(selectedRow,0).toString());
            pst.setString(3,jTable1.getValueAt(selectedRow,2).toString());
            pst.executeUpdate();
        }catch(Exception e){
        e.printStackTrace();
        }
         refresh();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
       int selectedRow=jTable1.getSelectedRow();
        Connection conn=ConnerDB();
        try{
        String sql = "update attend set C_ATTEND=? WHERE C_CLASS_NO=? AND C_STUDENT_ID=?";
            PreparedStatement pst = null;
            pst = conn.prepareStatement(sql);
            pst.setString(1,  "ABSENT");
            pst.setString(2, jTable1.getValueAt(selectedRow,0).toString());
            pst.setString(3,jTable1.getValueAt(selectedRow,2).toString());
            pst.executeUpdate();
        }catch(Exception e){
        e.printStackTrace();
        }
         refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATTNDENCE_GIVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATTNDENCE_GIVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATTNDENCE_GIVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATTNDENCE_GIVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATTNDENCE_GIVE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
